### ISSUE TITLE
Identify filtering criteria

### ISSUE THREAD

**Issue by MrSamsa42** [ActoKids/web-ui#26]
The API team has created an endpoint for filtering data returned by the API based on criteria submitted in search string parameters.  For example, 

This filters on contact_name, returning all events where contact_name = "Jonathan"
https://api-jona.2edusite.com/v1/events/eventsFilter?contact_name=Jonathan

This filters on contact_name AND contact_email
https://api-jona.2edusite.com/v1/events/eventsFilter?contact_name=Jonathan&contact_email=jradler@gmail.com

This filters on contact_name AND contact_email AND approver
https://api-jona.2edusite.com/v1/events/eventsFilter?contact_name=Jonathan&contact_email=jradler@gmail.com&approver=Zeus

Right now, the eventsFilter endpoint works with all event attributes in any additive combination (i.e. this AND that); it does not support something like, "cost less than 10", or "contact_name starts with W".  

It is difficult to write code that would allow for complicated ad hoc queries of dynamodb, so we would just like to cover the known cases.  If the web-ui requires filtering of events beyond that which has already been implemented, those queries must be identified and brought to the attention of the API team so that Lambda can be modified accordingly.  Else, this issue can be closed.

Keep in mind that some filtering can and should be done client-side (i.e. in the React code) (if this does not present security concerns!) as it will minimize Lambda and API gateway costs.

**Comment by coultergeist** [comment]
Jon, 
Looking into this now and will have more information Wednesday, March 6.
